services:
  OrderSQL:
    image: mysql
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./OrderSQL/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  OrderSvc:
    build: ./OrderSvc/
    image: order_svc
    ports:
      - 8087:8080
    networks:
      - ProjectNet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_healthy
  OrderCons:
    build: ./OrderCons/
    image: order_cons
    ports:
      - 8088:8080
    networks:
      - ProjectNet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_healthy
      OrderSvc:
        condition: service_started

networks:
  ProjectNet:
    external: true
  OrderNet: