services:
  LoginSQL:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./LoginSQL/:/docker-entrypoint-initdb.d
    networks:
      - LoginNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  LoginSvc:
    build: ./LoginSvc/
    image: login_svc
    ports:
      - 8085:8080
    networks:
      - ProjectNet
      - LoginNet
    depends_on: 
      LoginSQL:
        condition: service_healthy
  LoginCons:
    build: ./LoginCons/
    image: login_cons
    ports:
      - 8086:8080
    networks:
      - ProjectNet
      - LoginNet
    depends_on: 
      LoginSQL:
        condition: service_healthy
      LoginSvc:
        condition: service_started

networks:
  ProjectNet:
    external: true
  LoginNet: