services:
  StaffSQL:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./StaffSQL/:/docker-entrypoint-initdb.d
    networks:
      - StaffNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  StaffSvc:
    build: ./StaffSvc/
    image: staff_svc
    ports:
      - 8083:8080
    networks:
      - ProjectNet
      - StaffNet
    depends_on: 
      StaffSQL:
        condition: service_healthy
  StaffCons:
    build: ./StaffCons/
    image: staff_cons
    ports:
      - 8084:8080
    networks:
      - ProjectNet
      - StaffNet
    depends_on: 
      StaffSQL:
        condition: service_healthy
      StaffSvc:
        condition: service_started

networks:
  ProjectNet:
    external: true
  StaffNet: